export const FETCH_REPOS = 'FETCH_REPOS';
export const FETCH_REPOS_FULFILLED = 'FETCH_REPOS_FULFILLED';
export const FETCH_REPOS_REJECTED = 'FETCH_REPOS_REJECTED';
export const FETCH_REPOS_PENDING = 'FETCH_REPOS_PENDING';
export const SET_QUERY = 'SET_QUERY';
export const SET_SCOPE = 'SET_SCOPE';
export const SET_CURRENTPAGE = 'SET_CURRENTPAGE';

export const FETCH_ISSUES = 'FETCH_ISSUES';
export const FETCH_ISSUES_FULFILLED = 'FETCH_ISSUES_FULFILLED';
export const FETCH_ISSUES_REJECTED = 'FETCH_ISSUES_REJECTED';
export const FETCH_ISSUES_PENDING = 'FETCH_ISSUES_PENDING';

export const FETCH_ISSUE_SINGLE = 'FETCH_ISSUE_SINGLE';
export const FETCH_ISSUE_SINGLE_FULFILLED = 'FETCH_ISSUE_SINGLE_FULFILLED';
export const FETCH_ISSUE_SINGLE_REJECTED = 'FETCH_ISSUE_SINGLE_REJECTED';
export const FETCH_ISSUE_SINGLE_PENDING = 'FETCH_ISSUE_SINGLE_PENDING';

export const FETCH_ISSUE_COMMENTS = 'FETCH_ISSUE_COMMENTS';
export const FETCH_ISSUE_COMMENTS_FULFILLED = 'FETCH_ISSUE_COMMENTS_FULFILLED';
export const FETCH_ISSUE_COMMENTS_REJECTED = 'FETCH_ISSUE_COMMENTS_REJECTED';
export const FETCH_ISSUE_COMMENTS_PENDING = 'FETCH_ISSUE_COMMENTS_PENDING';
