export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_FULFILLED = 'FETCH_POSTS_FULFILLED';
export const FETCH_POSTS_REJECTED = 'FETCH_POSTS_REJECTED';
export const FETCH_POSTS_PENDING = 'FETCH_POSTS_PENDING';
export const SET_QUERY = 'SET_QUERY';
export const SET_SCOPE = 'SET_SCOPE';
export const SET_CURRENTPAGE = 'SET_CURRENTPAGE';
